# Site settings
title: Wanderson Policarpo
email: wpolicarpo@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
url: "https://wpolicarpo.github.io"
name: Wanderson Policarpo
job: Software Developer
company:
  name: Fusioneer
  site: http://fusioneer.com
location: Dublin, Ireland
credits: https://github.com/wpolicarpo/wpolicarpo.github.io#credits

# Build settings
markdown: kramdown
