# Site settings
title: Wanderson Policarpo
email: wpolicarpo@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
url: "https://wpolicarpo.github.io"
name: Wanderson Policarpo
job: Software Developer
location: Dublin, Ireland

# Build settings
markdown: kramdown
